---
title: "Teaching"
subtitle: "I'm currently teaching"
title-block-banner: false
toc: false
---


## COSC 366 - Introduction to Cybersecurity

::: {.grid}

:::

::: {.g-col-12 .g-col-md-10}

A broad introduction to cybersecurity concepts. The class will introduce basic topics core to understanding computer security including security goals, threat modeling, software security, operating system security, cryptography, network security, and human factors. Coursework focuses on helping students adapt a security aware mindset when designing, developing, and testing systems.

:::


## COSC 434/534 - Network Security

::: {.grid}

:::

::: {.g-col-12 .g-col-md-10}


In-depth introduction to core Internet and wireless technologies, related security concerns, common security vulnerabilities, and good security practices. Hands-on experience exploiting network protocols and communications, and setting up secure network connections.

:::



## COSC 230 - Computer Organization

::: {.grid}

:::

::: {.g-col-12 .g-col-md-10}

Gate level logic, binary number representation and arithmetic, data path and memory hierarchy with focus on code impact, parallel computing, instruction set architecture.

:::



## ECE 453/553 - Introduction to Computer Networks

::: {.grid}

:::

::: {.g-col-12 .g-col-md-10}

Introduction to the design and implementation of computer networks. Topics to be covered include layered network architecture, physical media, data link protocols, network routing, transport layer, network programming interfaces such as sockets, and applications. Examples will be primarily based on protocols in the Internet.

:::



## ECE 255 - Introduction to Logic Design of Digital Systems

::: {.grid}

:::

::: {.g-col-12 .g-col-md-10}

Standard codes, number systems, base conversions, and computer arithmetic. Boolean algebra, minimization and synthesis techniques for combinational and sequential logic. Use of VHDL for logic synthesis. Implementation of circuits using SSI, MSI, and LSI components. Includes Level 1 design projects which require laboratory work.

:::



